export default {
  en: {
    translation: {
      channels: {
        channels: 'Channels',
        remove: 'Remove',
        rename: 'Rename',
      },
      errors: {
        confirm: 'Passwords must match',
        exist: 'User already exists',
        length: 'From 3 to 20 characters',
        logError: 'Incorrect user name or password',
        netError: 'Network error',
        passMax: 'Maximum 20 characters',
        passMin: 'Minimum 6 characters',
        required: 'Required field',
        uniq: 'Must be uniq',
      },
      hexletChat: 'Hexlet Chat',
      login: {
        logIn: 'Log in',
        nickname: 'Nickname',
        noAccount: 'No account?',
        password: 'Password',
        signup: 'Registration',
      },
      mainPage: {
        logOut: 'Log out',
        send: 'Send',
      },
      modals: {
        addChannel: 'Create channel',
        cancel: 'Cancel',
        confirm: 'Are you sure?',
        remChannel: 'Remove channel',
        remove: 'Remove',
        renChannel: 'Rename channel',
        send: 'Send',
      },
      placeholders: {
        nickMin: 'From 3 to 20 characters',
        passConfirm: 'Passwords must match',
        passMin: 'Minimum 6 characters',
      },
      process: {
        loading: 'Loading...',
        removing: 'Removing...',
        sending: 'Sending...',
      },
      register: {
        confirm: 'Confirm password',
        password: 'Password',
        toSignup: 'Signup',
        username: 'User name',
      },
    },
  },
  ru: {
    translation: {
      channels: {
        channels: 'Каналы',
        remove: 'Удалить',
        rename: 'Переименовать',
      },
      errors: {
        confirm: 'Пароли должны совпадать',
        exist: 'Такой пользователь уже существует',
        length: 'От 3 до 20 символов',
        logError: 'Неверные имя пользователя или пароль',
        netError: 'Ошибка сети',
        passMax: 'Не более 20 символов',
        passMin: 'Не менее 6 символов',
        required: 'Обязательное поле',
        uniq: 'Должно быть уникальным',
      },
      hexletChat: 'Hexlet Chat',
      login: {
        logIn: 'Войти',
        nickname: 'Ваш ник',
        noAccount: 'Нет аккаунта?',
        password: 'Пароль',
        signup: 'Регистрация',
      },
      mainPage: {
        logOut: 'Выйти',
        send: 'Отправить',
      },
      modals: {
        addChannel: 'Добавить канал',
        cancel: 'Отменить',
        confirm: 'Уверены?',
        remChannel: 'Удалить канал',
        remove: 'Удалить',
        renChannel: 'Переименовать канал',
        send: 'Отправить',
      },
      placeholders: {
        nickMin: 'От 3 до 20 символов',
        passConfirm: 'Пароли должны совпадать',
        passMin: 'Не менее 6 символов',
      },
      process: {
        loading: 'Загрузка...',
        removing: 'Удаление...',
        sending: 'Отправка...',
      },
      register: {
        confirm: 'Подтвердите пароль',
        password: 'Пароль',
        toSignup: 'Зарегистрироваться',
        username: 'Имя пользователя',
      },
    },
  },
};
