export default {
  en: {
    translation: {
      errors: {
        length: 'From 3 to 20 characters',
        required: 'Required field',
        netError: 'Network error',
        uniq: 'Must be uniq',
        passMin: 'Minimum 6 characters',
        passMax: 'Maximum 20 characters',
        confirm: 'Passwords must match',
        logError: 'Incorrect user name or password',
        exist: 'User already exists',
      },
      hexletChat: 'Hexlet Chat',
      mainPage: {
        logOut: 'Log out',
        send: 'Send',
      },
      process: {
        removing: 'Removing...',
        sending: 'Sending...',
        loading: 'Loading...',
      },
      channels: {
        remove: 'Remove',
        rename: 'Rename',
        channels: 'Channels',
      },
      modals: {
        addChannel: 'Create channel',
        remChannel: 'Remove channel',
        renChannel: 'Rename channel',
        cancel: 'Cancel',
        remove: 'Remove',
        send: 'Send',
        confirm: 'Are you sure?',
      },
      register: {
        password: 'Password',
        username: 'User name',
        confirm: 'Confirm password',
        toSignup: 'Signup',
      },
      login: {
        nickname: 'Nickname',
        password: 'Password',
        logIn: 'Log in',
        noAccount: 'No account?',
        signup: 'Registration',
      },
      placeholders: {
        nickMin: 'From 3 to 20 characters',
        passMin: 'Minimum 6 characters',
        passConfirm: 'Passwords must match',
      },
    },
  },
  ru: {
    translation: {
      errors: {
        length: 'От 3 до 20 символов',
        required: 'Обязательное поле',
        netError: 'Ошибка сети',
        uniq: 'Должно быть уникальным',
        passMin: 'Не менее 6 символов',
        passMax: 'Не более 20 символов',
        confirm: 'Пароли должны совпадать',
        logError: 'Неверные имя пользователя или пароль',
        exist: 'Такой пользователь уже существует',
      },
      hexletChat: 'Hexlet Chat',
      mainPage: {
        logOut: 'Выйти',
        send: 'Отправить',
      },
      process: {
        removing: 'Удаление...',
        sending: 'Отправка...',
        loading: 'Загрузка...',
      },
      channels: {
        remove: 'Удалить',
        rename: 'Переименовать',
        channels: 'Каналы',
      },
      modals: {
        addChannel: 'Добавить канал',
        remChannel: 'Удалить канал',
        renChannel: 'Переименовать канал',
        cancel: 'Отменить',
        remove: 'Удалить',
        send: 'Отправить',
        confirm: 'Уверены?',
      },
      register: {
        password: 'Пароль',
        username: 'Имя пользователя',
        confirm: 'Подтвердите пароль',
        toSignup: 'Зарегистрироваться',
      },
      login: {
        nickname: 'Ваш ник',
        password: 'Пароль',
        logIn: 'Войти',
        noAccount: 'Нет аккаунта?',
        signup: 'Регистрация',
      },
      placeholders: {
        nickMin: 'От 3 до 20 символов',
        passMin: 'Не менее 6 символов',
        passConfirm: 'Пароли должны совпадать',
      },
    },
  },
};
