export default {
  translation: {
    counts: {
      key_0: '{{count}} сообщение',
      key_1: '{{count}} сообщения',
      key_2: '{{count}} сообщений',
    },
    channels: {
      channels: 'Каналы',
      remove: 'Удалить',
      rename: 'Переименовать',
    },
    errors: {
      confirm: 'Пароли должны совпадать',
      exist: 'Такой пользователь уже существует',
      length: 'От 3 до 14 символов',
      logError: 'Неверные имя пользователя или пароль',
      netError: 'Ошибка сети',
      passMax: 'Не более 20 символов',
      passMin: 'Не менее 6 символов',
      required: 'Обязательное поле',
      someError: 'Ошибка',
      uniq: 'Должно быть уникальным',
    },
    hexletChat: 'Hexlet Chat',
    login: {
      logIn: 'Войти',
      nickname: 'Ваш ник',
      noAccount: 'Нет аккаунта?',
      password: 'Пароль',
      signup: 'Регистрация',
    },
    mainPage: {
      logOut: 'Выйти',
      send: 'Отправить',
    },
    modals: {
      addChannel: 'Добавить канал',
      cancel: 'Отменить',
      confirm: 'Уверены?',
      remChannel: 'Удалить канал',
      remove: 'Удалить',
      renChannel: 'Переименовать канал',
      send: 'Отправить',
    },
    placeholders: {
      addChannel: 'От 3 to 14 символов',
      nickMin: 'От 3 до 20 символов',
      passConfirm: 'Пароли должны совпадать',
      passMin: 'Не менее 6 символов',
    },
    process: {
      addMessage: 'Введите сообщение...',
      loading: 'Загрузка...',
      removing: 'Удаление...',
      sending: 'Отправка...',
    },
    register: {
      confirm: 'Подтвердите пароль',
      password: 'Пароль',
      registry: 'Регистрация',
      toSignup: 'Зарегистрироваться',
      username: 'Имя пользователя',
    },
    theme: {
      dark: 'Тёмная тема',
      light: 'Светлая тема',
    },
  },
};
